---

# This task is invoked during the invocation of the playbook below:
#
# ansible-playbook -i host_file dbimage-make.yml -u ubuntu -c ssh
#
# It is invoked on the deployer node under the root account

- name: Set image name
  set_fact:
    outputImage: "{{ hostvars[groups['dib'][0]].outputImage.split('.')[0] }}"

- name: Convert qcow2 image to raw format
  shell: qemu-img convert -f qcow2 -O raw "{{ item }}.qcow2" "{{ item }}.img"
  register: qemurc
  with_items: "{{ baseDir }}/images/{{ outputImage }}"
