---
# This task is invoked during the invocation of the playbook below:
#
# ansible-playbook -i host_file dbimage-make.yml -u ubuntu -c ssh
#
# This is invoked on the dibvm under the ubuntu user
#
# It is only invoked for trusty builds when the user exports DIB_RELEASE=trusty.

- name: Define distro package name for mariadb
  set_fact:
    pkgDistroName: 'mariadb-server'
    pkgDistroVersion: '5.5.54'
  when: dbName == 'mariadb'

- name: Define distro package name for mongodb
  set_fact:
    pkgDistroName: 'mongodb-server'
    pkgDistroVersion: '2.4.9'
  when: dbName == 'mongodb'

- name: Define distro package name for mysql
  set_fact:
    pkgDistroName: 'mysql-server'
    pkgDistroVersion: '5.5.54'
  when: dbName == 'mysql'

- name: Define distro package name for postgresql
  set_fact:
    pkgDistroName: 'postgresql-9.5'
    pkgDistroVersion: '9.5.2'
  when: dbName == 'postgresql'

- name: Define distro package name for redis
  set_fact:
    pkgDistroName: 'redis-server'
    pkgDistroVersion: '2.8.4'
  when: dbName == 'redis'

- name: Set the short form of the database version
  set_fact:
    dbVersion: "{{ '.'.join(pkgDistroVersion.split(':', 1)[-1].split('.',2)[:-1]) | default('') }}"
  when: not dbVersion

- debug: var=dbVersion
