---
# Copyright 2016 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Use the lxc-openstack aa profile
  lxc_container:
    name: "{{ container_name }}"
    container_config:
      - "lxc.aa_profile=lxc-openstack"
  delegate_to: "{{ physical_host }}"
  when: not is_metal | bool
  register: container_config
  tags:
    - lxc-aa-profile

- name: Wait for container ssh
  wait_for:
    port: "22"
    delay: "{{ ssh_delay }}"
    search_regex: "OpenSSH"
    host: "{{ ansible_ssh_host }}"
  delegate_to: "{{ physical_host }}"
  when: container_config is defined and container_config | changed
  register: ssh_wait_check
  until: ssh_wait_check | success
  retries: 3
  tags:
    - ssh-wait

- name: Update apt sources
  apt:
    update_cache: yes
    cache_valid_time: 600
  register: apt_update
  until: apt_update|success
  retries: 5
  delay: 2
  tags:
    - trove-pkgs
    - trove-apt-pkgs

- include: pkgs.yml

- group: name=trove state=present
- user: name=trove createhome=no group=trove state=present

- include: add_service.yml
  when: inventory_hostname == groups['trove_all'][0]

- name: Create  directories
  file:
    dest: "{{ item.dest }}"
    state: "directory"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    force: "yes"
  with_items:
     - { dest: "/var/log/trove", mode: "0755", owner: "trove", group: "trove" }
     - { dest: "/var/cache/trove", mode: "0700", owner: "trove", group: "trove" }
     - { dest: "/etc/trove", mode: "0755", owner: "trove", group: "trove" }
     - { dest: "/var/lib/trove", mode: "0755", owner: "trove", group: "trove" }
  when: not is_metal | bool
  tags:
    - trove-dirs

- name: touch log files
  file:
    path: /var/log/trove/{{ item }}
    state: touch
    owner: trove
    group: trove
    mode: 0644
  with_items:
    - api.log
    - trove.log
    - taskmanager.log
    - conductor.log
  tags:
    - trove-dirs

- name: Grab private ssh key
  set_fact:
    private_ssh_key: "{{ lookup('file', '/root/.ssh/id_rsa') }}"
- name: Drop in private ssh key
  copy:
    content: "{{ private_ssh_key }}"
    dest: /root/.ssh/id_rsa
    mode: 0600
    owner: root
    group: root

- include: add_infra_net.yml

- name: Copy conf files
  template:
    src: "{{ item }}"
    dest: "/etc/trove//{{ item }}"
    owner: "root"
    group: "root"
  with_items:
    - trove.conf
    - trove-conductor.conf
    - trove-taskmanager.conf
    - api-paste.ini
  tags:
   - conf-file

- name: Create trove services init files
  template:
    src: init-{{ item }}
    dest: /etc/init/{{ item }}
    owner: "root"
    group: "root"
  with_items:
   - trove-conductor.conf
   - trove-api.conf
   - trove-taskmanager.conf

  tags:
   - conf-file

- name: Trove db_sync
  command: su -s /bin/sh -c "trove-manage db_sync" trove
  tags:
   - restart-services

- name: Restart trove-api
  service:
    name: trove-api
    state: restarted
  tags:
   - restart-services

- name: Restart trove-taskmanager
  service:
    name: trove-taskmanager
    state: restarted
  tags:
   - restart-services

- name: Restart trove-conductor
  service:
    name: trove-conductor
    state: restarted
  tags:
   - restart-services

