---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install glance server
  hosts: glance_all
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 20
  user: root
  pre_tasks:
    - include: common-tasks/os-lxc-container-setup.yml
      static: no
      vars:
        list_of_bind_mounts:
          - bind_dir_path: "/var/lib/glance/images"
            mount_path: "/openstack/{{ inventory_hostname }}"
      when:
        - glance_default_store == "file"
        - (glance_nfs_client is not defined) or (glance_nfs_client | length == 0)
    - include: common-tasks/os-lxc-container-setup.yml
      static: no
      when: (glance_default_store != "file") or (glance_nfs_client is defined)
    - include: common-tasks/rabbitmq-vhost-user.yml
      static: no
      vars:
        user: "{{ glance_rabbitmq_userid }}"
        password: "{{ glance_rabbitmq_password }}"
        vhost: "{{ glance_rabbitmq_vhost }}"
        _rabbitmq_host_group: "{{ glance_rabbitmq_host_group }}"
      when:
        - inventory_hostname == groups['glance_all'][0]
        - groups[glance_rabbitmq_host_group] | length > 0
    - include: common-tasks/rabbitmq-vhost-user.yml
      static: no
      vars:
        user: "{{ glance_rabbitmq_telemetry_userid }}"
        password: "{{ glance_rabbitmq_telemetry_password }}"
        vhost: "{{ glance_rabbitmq_telemetry_vhost }}"
        _rabbitmq_host_group: "{{ glance_rabbitmq_telemetry_host_group }}"
      when:
        - glance_ceilometer_enabled | bool
        - inventory_hostname == groups['glance_all'][0]
        - groups[glance_rabbitmq_telemetry_host_group] is defined
        - groups[glance_rabbitmq_telemetry_host_group] | length > 0
        - groups[glance_rabbitmq_telemetry_host_group] != groups[glance_rabbitmq_host_group]
    - include: common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-glance"
            dest: "/var/log/glance"
    - include: common-tasks/mysql-db-user.yml
      static: no
      vars:
        user_name: "{{ glance_galera_user }}"
        password: "{{ glance_container_mysql_password }}"
        login_host: "{{ glance_galera_address }}"
        db_name: "{{ glance_galera_database }}"
      when: inventory_hostname == groups['glance_all'][0]
    - include: common-tasks/package-cache-proxy.yml
  roles:
    - role: "os_glance"
      glance_venv_tag: "{{ openstack_release }}"
      glance_venv_download_url: "{{ openstack_repo_url }}/venvs/{{ openstack_release }}/{{ ansible_distribution | lower }}/glance-{{ openstack_release }}-{{ ansible_architecture | lower }}.tgz"
    - role: "openstack_openrc"
      tags:
        - openrc
    - role: "ceph_client"
      openstack_service_system_user: "{{ glance_system_user_name }}"
      openstack_service_venv_bin: "/openstack/venvs/glance-{{ openstack_release }}/bin"
      tags:
        - ceph
      when:
        - inventory_hostname in groups['glance_api']
        - "{{ 'rbd' in [glance_default_store | default('none')] + glance_additional_stores | default([]) }}"
    - role: "rsyslog_client"
      rsyslog_client_log_rotate_file: glance_log_rotate
      rsyslog_client_log_dir: "/var/log/glance"
      rsyslog_client_config_name: "99-glance-rsyslog-client.conf"
      tags:
        - rsyslog
    - role: "system_crontab_coordination"
      tags:
        - crontab
  vars:
    is_metal: "{{ properties.is_metal|default(false) }}"
    glance_galera_user: glance
    glance_galera_database: glance
    glance_galera_address: "{{ galera_address }}"
  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - glance
