---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install heat server
  hosts: heat_all
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 20
  user: root
  pre_tasks:
    - include: common-tasks/os-lxc-container-setup.yml
    - include: common-tasks/rabbitmq-vhost-user.yml
      static: no
      vars:
        user: "{{ heat_rabbitmq_userid }}"
        password: "{{ heat_rabbitmq_password }}"
        vhost: "{{ heat_rabbitmq_vhost }}"
        _rabbitmq_host_group: "{{ heat_rabbitmq_host_group }}"
      when:
        - inventory_hostname == groups['heat_all'][0]
        - groups[heat_rabbitmq_host_group] | length > 0
    - include: common-tasks/rabbitmq-vhost-user.yml
      static: no
      vars:
        user: "{{ heat_rabbitmq_telemetry_userid }}"
        password: "{{ heat_rabbitmq_telemetry_password }}"
        vhost: "{{ heat_rabbitmq_telemetry_vhost }}"
        _rabbitmq_host_group: "{{ heat_rabbitmq_telemetry_host_group }}"
      when:
        - heat_ceilometer_enabled | bool
        - inventory_hostname == groups['heat_all'][0]
        - groups[heat_rabbitmq_telemetry_host_group] is defined
        - groups[heat_rabbitmq_telemetry_host_group] | length > 0
        - groups[heat_rabbitmq_telemetry_host_group] != groups[heat_rabbitmq_host_group]
    - include: common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-heat"
            dest: "/var/log/heat"
    - include: common-tasks/mysql-db-user.yml
      static: no
      vars:
        user_name: "{{ heat_galera_user }}"
        password: "{{ heat_container_mysql_password }}"
        login_host: "{{ heat_galera_address }}"
        db_name: "{{ heat_galera_database }}"
      when: inventory_hostname == groups['heat_all'][0]
    - include: common-tasks/package-cache-proxy.yml
  roles:
    - role: "os_heat"
      heat_venv_tag: "{{ openstack_release }}"
      heat_venv_download_url: "{{ openstack_repo_url }}/venvs/{{ openstack_release }}/{{ ansible_distribution | lower }}/heat-{{ openstack_release }}-{{ ansible_architecture | lower }}.tgz"
    - role: "rsyslog_client"
      rsyslog_client_log_rotate_file: heat_log_rotate
      rsyslog_client_log_dir: "/var/log/heat"
      rsyslog_client_config_name: "99-heat-rsyslog-client.conf"
      tags:
        - rsyslog
    - role: "system_crontab_coordination"
      tags:
        - crontab
  vars_files:
    - defaults/repo_packages/openstack_services.yml
  vars:
    is_metal: "{{ properties.is_metal|default(false) }}"
    heat_galera_user: heat
    heat_galera_database: heat
    heat_galera_address: "{{ galera_address }}"
  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - heat
