---
# Copyright 2016 IBM Corp.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

  - name: Set starting values for device lists and mount points.
    set_fact:
      account_devices: {}
      container_devices: {}
      object_devices: {}
      metadata_mount_point: {}
      object_mount_point: {}

  - name: Set metadata domain-settings shortcut for non-converged case.
    set_fact:
      template_md_ds: "{{ node_templates['swift-metadata']['domain-settings'] | default({}) }}"
    when: node_templates['swift-metadata'] is defined

  - name: Set metadata domain-settings shortcut for converged case.
    set_fact:
      template_md_ds: {}
    when: node_templates['swift-metadata'] is not defined

  - name: Set other domain-settings shortcuts.
    set_fact:
      template_obj_ds: "{{ node_templates['swift-object']['domain-settings'] | default({}) }}"
      host_md_ds: "{{ hostvars[inventory_hostname]['domain_settings'] | default({}) }}"
      host_obj_ds: "{{ hostvars[inventory_hostname]['domain_settings'] | default({}) }}"

  - name: Set Swift metadata host device lists and mountpoint.
    set_fact:
      account_devices: "{{ host_md_ds['account-ring-devices'] | default(template_md_ds['account-ring-devices']) | default({}) }}"
      container_devices: "{{ host_md_ds['container-ring-devices'] | default(template_md_ds['container-ring-devices']) | default({}) }}"
      metadata_mount_point: "{{ host_md_ds['mount-point'] | default(template_md_ds['mount-point']) | default('/srv/node') }}"
    when:
      - groups['swift-metadata'] is defined
      - inventory_hostname in groups['swift-metadata']

  - name: Set Swift object host device lists and mountpoint.
    set_fact:
      account_devices: "{{ host_obj_ds['account-ring-devices'] | default(template_obj_ds['account-ring-devices']) | default({}) }}"
      container_devices: "{{ host_obj_ds['container-ring-devices'] | default(template_obj_ds['container-ring-devices']) | default({}) }}"
      metadata_mount_point: "{{ host_obj_ds['mount-point'] | default(template_obj_ds['mount-point']) | default('/srv/node') }}"
      object_devices: "{{ host_obj_ds['object-ring-devices'] | default(template_obj_ds['object-ring-devices']) | default({}) }}"
      object_mount_point: "{{ host_obj_ds['mount-point'] | default(template_obj_ds['mount-point']) | default('/srv/node') }}"
    when: inventory_hostname in groups['swift-object']

  - name: Print device list settings.
    debug:
      msg: "{{ item }}"
    with_items:
      - "account_devices={{ account_devices }}"
      - "container_devices={{ container_devices }}"
      - "metadata_mount_point={{ metadata_mount_point }}"
      - "object_devices={{ object_devices }}"
      - "object_mount_point={{ object_mount_point }}"
      - "group_names={{ group_names }}"

